### ISSUE TITLE
imports.html test failing on master with polyfilled custom elements

### ISSUE THREAD

**Issue by valdrinkoshi** [PolymerElements/iron-resizable-behavior#37]
`test/imports.html` currently failing in master:
https://github.com/PolymerElements/iron-resizable-behavior/blob/45b57d62062a19597ba4604749b16a07b3e8864c/test/imports.html#L22-L30

This looks broken since the update to custom-elements v1.0.2 - I suspect https://github.com/webcomponents/custom-elements/pull/108 broke it.

The issue is that `iron-request-resize-notifications` is fired too early by the child, because the parent is not upgraded yet (https://github.com/webcomponents/custom-elements/issues/15).
https://github.com/PolymerElements/iron-resizable-behavior/blob/45b57d62062a19597ba4604749b16a07b3e8864c/iron-resizable-behavior.html#L201

To workaround https://github.com/webcomponents/custom-elements/issues/15, we wait for the document to be done loading: https://github.com/PolymerElements/iron-resizable-behavior/blob/45b57d62062a19597ba4604749b16a07b3e8864c/iron-resizable-behavior.html#L188-L194

This is no longer enough since custom-elements v1.0.2, which will upgrade elements before `flush` is called (done in https://github.com/webcomponents/custom-elements/pull/108).

**Comment by valdrinkoshi** [comment]
@bicknellr @cdata @kevinpschaaf FYI

I'm not sure how to approach this: 
1) we could fire the event asynchronously, as @kevinpschaaf [suggested](https://github.com/webcomponents/custom-elements/issues/15#issuecomment-258992354)
2) we could just not support the case of unordered imports, and expect the user to register custom elements in the right order

I'm hesitant about 1), as that would finally delay the firing of `iron-resize` event, hence potentially duplicate layout work for elements doing relayout work when the event is fired.

**Comment by bicknellr** [comment]
This is fixed as of #42.
