### ISSUE TITLE
Uncaught TypeError: Cannot read property 'bind' of undefined

### ISSUE THREAD

**Issue by ystreibel** [PolymerElements/iron-resizable-behavior#4]
Hi,

I have this error when I use polyserve to test the demo.

Polymer.attached @ x-app.html:59 :

<code>
    attached: function() {
      this.async(this.resizeAction, 1);
    },
</code>

You have to replace those lines by :

<code>
    attached: function() {
      this.async(this._onIronResize, 1);
    },
</code>

**Comment by notwaldorf** [comment]
Not reproducible with the latest release
